<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_ModeSelector" Id="{dc4d674e-38ac-46d6-a68e-c41c72f8ff42}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ModeSelector
VAR_INPUT
	bControlBox : BOOL;
END_VAR
VAR_OUTPUT
END_VAR
VAR
	fbMode : FB_ModeVisualization;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[IF NOT(bControlBox) THEN
	IF NOT(G_VB.bOn) THEN
		fbMode.Off(TRUE);
		fbMode.Manual(FALSE);
		fbMode.Auto(FALSE);
	ELSIF G_VB.bOn AND NOT(G_VB.bAuto) THEN
		fbMode.Off(FALSE);
		fbMode.Manual(TRUE);
		fbMode.Auto(FALSE);
	ELSIF G_VB.bOn AND G_VB.bAuto THEN
		fbMode.Off(FALSE);
		fbMode.Manual(FALSE);
		fbMode.Auto(TRUE);
	ELSE
		fbMode.Off(FALSE);
		fbMode.Manual(FALSE);
		fbMode.Auto(FALSE);
	END_IF
END_IF]]></ST>
    </Implementation>
    <LineIds Name="FB_ModeSelector">
      <LineId Id="9" Count="0" />
      <LineId Id="17" Count="0" />
      <LineId Id="19" Count="0" />
      <LineId Id="22" Count="2" />
      <LineId Id="27" Count="1" />
      <LineId Id="26" Count="0" />
      <LineId Id="30" Count="2" />
      <LineId Id="29" Count="0" />
      <LineId Id="33" Count="0" />
      <LineId Id="35" Count="1" />
      <LineId Id="34" Count="0" />
      <LineId Id="20" Count="0" />
      <LineId Id="18" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>