<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Joystick" Id="{243de92e-bef9-41b7-8569-8f7e3bf2002f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Joystick
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>