<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_ManualControl" Id="{030c0b1e-cfb9-4458-97b6-7b35e272d107}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ManualControl
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>