<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="P_Task2" Id="{9ed0eceb-1ce7-484d-b635-a4528063a015}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_Task2
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="P_Task2">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>